### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/nativesintech.org#83]
## Background

It has been about a year since the site has been developed and it needs some improvements from an aesthetic as well as a functional point of view. I think the site can be improved in two ways: (1) Move over to using Next.js with TypeScript & TailwindCSS and (2) use ghost as our headless CMS. 

### Move to Next.js with TypeScript support and TailwindCSS

This project was originally developed using Phenomic, but it doesn't look like it will be maintained in the future :( https://github.com/phenomic/phenomic/issues/1286. For this reason, it makes sense to move the project over to using Next.js. There are bindings out there to still use Reason, which would make the transition easier, but it's more fun to build something from scratch am I right? 

TailwindCSS is a utility first CSS framework. It makes it super easy to build beautiful sites using their utilities and they also have great editor support. When I started the project it was a goal of mine to develop my own CSS framework and although it was a nice learning experience it was not something that I could maintain in the long term. So going with TailwindCSS I think is a safe bet going forward.

ReasonML is a wonderful language but there is a learning curve to using it. It's still in its infancy and I would like to see other people contribute to the codebase other than myself. TypeScript is being adopted at a quick rate in the web dev industry and even though the types are terrible at times, it's where many devs are at right now so I need to meet them there.

### Ghost CMS

It seemed fine when I first started that the CMS would be the code itself. However, this limits the number of contributors to the blog. I think the CMS should open up opportunities for other people to write for it and Ghost CMS will do that. It also has support for Next.js to provide headless CMS content so we can continue to use the JAM stack and get excellent performance.

## Todos

These changes will take place over a series of steps. First, move the project over to Next.js and build out the current pages we use.

| Issue | PR |Details | Status |
|-------|----|-----|--------|
|  #84  | #88, #89 | Next.js skeleton (TailwindCSS and TS) | ✅ |
|  #85  | #95, #98, #100 | Make Header component | ✅ |
|  #86  | #95, #98 | Make Footer component | ✅ |
|  #87  | #95, #99 | Make Home page        | ❎ |
|       | #95      | Make About page       | ❎ |
|       | #99      | Make Donations page   | ❎ |
|       | #95, #106| Make Awesome page     | ❎ |
|       | #95      | Make Conference page  | ❎ |
|       | 9ed7d1d  | Setup Ghost CMS backend | ✅ |
|       | 9ed7d1d  | Move all blogs posts to Ghost CMS | ✅ |
|       |          | Move conference details to Ghost CMS | ❌ |
|       | #102     | Documentation | ❎ |
|       |          | Polish and deploy | ❌ | 

| Status | Meaning |  
|--- |----|
|  ✅ | Done |
|  ❎ | In Progress |
|  ❌ | Not Started |

**Comment by kylemh** [comment]
Hello! I'm the maintainer for the front-end repo of [Operation Code](https://operationcode.org/). The [repository](https://github.com/OperationCode/front-end) uses a very similar setup (Next.js with Vanilla CSS + PostCSS). I just wanna make sure I'm reading correctly that it doesn't need to use ReasonML? I don't mind doing the first 3 bullets if I can use TypeScript!

**Comment by arecvlohe** [comment]
> I just wanna make sure I'm reading correctly that it doesn't need to use ReasonML?

@kylemh You read that correctly! We are moving away from ReasonML and towards TypeScript. Thanks for helping! If you have an questions then feel free to join us on Slack: http://nativesintech.herokuapp.com/.

**Comment by arecvlohe** [comment]
#110
