### ISSUE TITLE
Make v2 Header component

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/nativesintech.org#85]
## Problem

The header component from v1 was created with the semi css framework that I created. Instead it should be created with TailwindCSS. It might help to use storybook for this as well so that component can be build in isolation.

## Depends On

#84 

## Design

![Screen Shot 2020-01-20 at 22 31 40](https://user-images.githubusercontent.com/9747933/72775673-e63bb680-3bd4-11ea-9db2-7c89211b0f2f.png)

## Acceptance Criteria

- [x] Header looks like v1
- [x] Header is made using TailwindCSS
- [x] Header link styles are updated
- [x] Header is mobile responsive
- [ ] NiT icon in the top left is replaced with computer svg icon
- [ ] Computer svg icon colors are update to match tailwind css (teal-400, gray-800)

**Comment by jorgebustamante** [comment]
I’ll work on the header!

**Comment by arecvlohe** [comment]
@all-contributors add @jorgebustamante code

**Comment by arecvlohe** [comment]
This work is nearly done. Just need to update the icon in the top left and to change the colors of it to match the tailwindcss colors we are using

**Comment by arecvlohe** [comment]
Added in #100
