### ISSUE TITLE
Make v2 Footer component

### ISSUE THREAD

**Issue by arecvlohe** [nativesintech/nativesintech.org#86]
## Problem

The footer component was made with my personal css framework. It should be updated to use TailwindCSS instead.

## Depends On

#84 

## Design

![Screen Shot 2020-01-20 at 22 35 02](https://user-images.githubusercontent.com/9747933/72775734-2438da80-3bd5-11ea-8f98-dd436853be71.png)

## Acceptance Criteria

- [x] Footer looks like v1
- [x] Footer is made with TailwindCSS
- [ ] Figure out where Netlify's logo goes without it looking weird :)

**Comment by jorgebustamante** [comment]
I’ll get working on this rn!

**Comment by arecvlohe** [comment]
I added the footer but we need to figure out where netlify's logo goes

**Comment by arecvlohe** [comment]
Added in #100
